# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ATEC.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1188, 799)
        MainWindow.setMinimumSize(QtCore.QSize(800, 550))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/PlatinumLogo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color:transparent;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_61 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_61.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        self.frame_top = QtWidgets.QFrame(self.centralwidget)
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top.setObjectName("frame_top")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.frame_top)
        self.gridLayout_24.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.frame_top_east = QtWidgets.QFrame(self.frame_top)
        self.frame_top_east.setMinimumSize(QtCore.QSize(0, 55))
        self.frame_top_east.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_top_east.setStyleSheet("background-color: rgb(205, 220, 255);")
        self.frame_top_east.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_east.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_top_east.setObjectName("frame_top_east")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_top_east)
        self.horizontalLayout_10.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_appname = QtWidgets.QFrame(self.frame_top_east)
        self.frame_appname.setStyleSheet("background-color: rgb(205, 220, 255);")
        self.frame_appname.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_appname.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_appname.setObjectName("frame_appname")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_appname)
        self.verticalLayout_11.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_System = QtWidgets.QLabel(self.frame_appname)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_System.setFont(font)
        self.label_System.setStyleSheet("color:rgb(255,255,255);\n"
"color: rgb(0, 0, 0);")
        self.label_System.setAlignment(QtCore.Qt.AlignCenter)
        self.label_System.setObjectName("label_System")
        self.verticalLayout_11.addWidget(self.label_System)
        self.horizontalLayout_10.addWidget(self.frame_appname, 0, QtCore.Qt.AlignHCenter)
        self.frame_date = QtWidgets.QFrame(self.frame_top_east)
        self.frame_date.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_date.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_date.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(221, 245, 255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.frame_date.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_date.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_date.setObjectName("frame_date")
        self.verticalLayout_89 = QtWidgets.QVBoxLayout(self.frame_date)
        self.verticalLayout_89.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_89.setSpacing(0)
        self.verticalLayout_89.setObjectName("verticalLayout_89")
        self.label_date = QtWidgets.QLabel(self.frame_date)
        self.label_date.setMinimumSize(QtCore.QSize(0, 0))
        self.label_date.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_date.setFont(font)
        self.label_date.setStyleSheet("QLabel {\n"
"    border: none;\n"
"    color: black; /* or any color you prefer for the text */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: rgb(221, 245, 255);\n"
"\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    background-color: rgba(0,0,0,0);\n"
"}\n"
"\n"
"")
        self.label_date.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_date.setMidLineWidth(100)
        self.label_date.setText("")
        self.label_date.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date.setObjectName("label_date")
        self.verticalLayout_89.addWidget(self.label_date)
        self.horizontalLayout_10.addWidget(self.frame_date)
        self.gridLayout_24.addWidget(self.frame_top_east, 0, 1, 1, 1)
        self.frame_toodle = QtWidgets.QFrame(self.frame_top)
        self.frame_toodle.setMinimumSize(QtCore.QSize(180, 55))
        self.frame_toodle.setMaximumSize(QtCore.QSize(180, 120))
        self.frame_toodle.setStyleSheet("background:rgb(0,143,150);")
        self.frame_toodle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_toodle.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_toodle.setObjectName("frame_toodle")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_toodle)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.PB_Menu = QtWidgets.QPushButton(self.frame_toodle)
        self.PB_Menu.setMinimumSize(QtCore.QSize(180, 55))
        self.PB_Menu.setMaximumSize(QtCore.QSize(180, 55))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.PB_Menu.setFont(font)
        self.PB_Menu.setStyleSheet("\n"
"QPushButton {\n"
"    border: none;\n"
"    background-color: rgb(203, 203, 255);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(0,143,150);\n"
"\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgba(0,0,0,0);\n"
"}")
        self.PB_Menu.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Resource/icons/icons8-menu-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_Menu.setIcon(icon1)
        self.PB_Menu.setIconSize(QtCore.QSize(30, 30))
        self.PB_Menu.setFlat(True)
        self.PB_Menu.setObjectName("PB_Menu")
        self.verticalLayout_10.addWidget(self.PB_Menu)
        self.gridLayout_24.addWidget(self.frame_toodle, 0, 0, 1, 1)
        self.verticalLayout_61.addWidget(self.frame_top)
        self.frame_bottom = QtWidgets.QFrame(self.centralwidget)
        self.frame_bottom.setStyleSheet("")
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_bottom.setObjectName("frame_bottom")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_bottom)
        self.verticalLayout_14.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.splitter = QtWidgets.QSplitter(self.frame_bottom)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame_bottom_west = QtWidgets.QFrame(self.splitter)
        self.frame_bottom_west.setMinimumSize(QtCore.QSize(180, 0))
        self.frame_bottom_west.setMaximumSize(QtCore.QSize(180, 16777215))
        self.frame_bottom_west.setStyleSheet("background-color: rgb(205, 220, 255);")
        self.frame_bottom_west.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bottom_west.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_bottom_west.setObjectName("frame_bottom_west")
        self.verticalLayout_48 = QtWidgets.QVBoxLayout(self.frame_bottom_west)
        self.verticalLayout_48.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_48.setSpacing(0)
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.frame_Sys_menu = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_Sys_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_Sys_menu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_Sys_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Sys_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Sys_menu.setObjectName("frame_Sys_menu")
        self.verticalLayout_95 = QtWidgets.QVBoxLayout(self.frame_Sys_menu)
        self.verticalLayout_95.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_95.setSpacing(0)
        self.verticalLayout_95.setObjectName("verticalLayout_95")
        self.frame_Sys = QtWidgets.QFrame(self.frame_Sys_menu)
        self.frame_Sys.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_Sys.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_Sys.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Sys.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Sys.setObjectName("frame_Sys")
        self.verticalLayout_107 = QtWidgets.QVBoxLayout(self.frame_Sys)
        self.verticalLayout_107.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_107.setSpacing(0)
        self.verticalLayout_107.setObjectName("verticalLayout_107")
        self.PB_System = QtWidgets.QPushButton(self.frame_Sys)
        self.PB_System.setMinimumSize(QtCore.QSize(180, 50))
        self.PB_System.setMaximumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PB_System.setFont(font)
        self.PB_System.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: none;    \n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color: rgb(244, 255, 242);\n"
"                                      \n"
"}\n"
"QPushButton:focus{\n"
"  background-color: rgb(244, 255, 242);\n"
"}\n"
"QPushButton:pressed\n"
" {\n"
"background-color: rgb(244, 255, 242);\n"
"                                 }\n"
"")
        self.PB_System.setIconSize(QtCore.QSize(22, 22))
        self.PB_System.setCheckable(True)
        self.PB_System.setFlat(True)
        self.PB_System.setObjectName("PB_System")
        self.verticalLayout_107.addWidget(self.PB_System, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_95.addWidget(self.frame_Sys, 0, QtCore.Qt.AlignHCenter)
        self.sys_below_frame = QtWidgets.QFrame(self.frame_Sys_menu)
        self.sys_below_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.sys_below_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sys_below_frame.setStyleSheet("background-color: rgb(226, 233, 255);")
        self.sys_below_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sys_below_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sys_below_frame.setObjectName("sys_below_frame")
        self.verticalLayout_96 = QtWidgets.QVBoxLayout(self.sys_below_frame)
        self.verticalLayout_96.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_96.setSpacing(0)
        self.verticalLayout_96.setObjectName("verticalLayout_96")
        self.verticalLayout_95.addWidget(self.sys_below_frame, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_48.addWidget(self.frame_Sys_menu)
        self.frame_SubSys_Menu = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_SubSys_Menu.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_SubSys_Menu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_SubSys_Menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_SubSys_Menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_SubSys_Menu.setObjectName("frame_SubSys_Menu")
        self.verticalLayout_97 = QtWidgets.QVBoxLayout(self.frame_SubSys_Menu)
        self.verticalLayout_97.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_97.setSpacing(0)
        self.verticalLayout_97.setObjectName("verticalLayout_97")
        self.frame_subsystem = QtWidgets.QFrame(self.frame_SubSys_Menu)
        self.frame_subsystem.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_subsystem.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_subsystem.setStyleSheet("")
        self.frame_subsystem.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_subsystem.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_subsystem.setObjectName("frame_subsystem")
        self.verticalLayout_106 = QtWidgets.QVBoxLayout(self.frame_subsystem)
        self.verticalLayout_106.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_106.setSpacing(0)
        self.verticalLayout_106.setObjectName("verticalLayout_106")
        self.PB_OCR_IMAGE = QtWidgets.QPushButton(self.frame_subsystem)
        self.PB_OCR_IMAGE.setMinimumSize(QtCore.QSize(180, 50))
        self.PB_OCR_IMAGE.setMaximumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PB_OCR_IMAGE.setFont(font)
        self.PB_OCR_IMAGE.setStyleSheet("QPushButton{\n"
"border: none;    \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(244, 255, 242);                                      \n"
"}\n"
"QPushButton:focus{\n"
" background-color: rgb(244, 255, 242);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(244, 255, 242);\n"
"}\n"
"")
        self.PB_OCR_IMAGE.setIconSize(QtCore.QSize(22, 22))
        self.PB_OCR_IMAGE.setCheckable(True)
        self.PB_OCR_IMAGE.setFlat(True)
        self.PB_OCR_IMAGE.setObjectName("PB_OCR_IMAGE")
        self.verticalLayout_106.addWidget(self.PB_OCR_IMAGE)
        self.verticalLayout_97.addWidget(self.frame_subsystem, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_48.addWidget(self.frame_SubSys_Menu)
        self.frame_Calib = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_Calib.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_Calib.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_Calib.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Calib.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Calib.setObjectName("frame_Calib")
        self.verticalLayout_99 = QtWidgets.QVBoxLayout(self.frame_Calib)
        self.verticalLayout_99.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_99.setSpacing(0)
        self.verticalLayout_99.setObjectName("verticalLayout_99")
        self.frame_calibration = QtWidgets.QFrame(self.frame_Calib)
        self.frame_calibration.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_calibration.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_calibration.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_calibration.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_calibration.setObjectName("frame_calibration")
        self.verticalLayout_109 = QtWidgets.QVBoxLayout(self.frame_calibration)
        self.verticalLayout_109.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_109.setSpacing(0)
        self.verticalLayout_109.setObjectName("verticalLayout_109")
        self.verticalLayout_99.addWidget(self.frame_calibration)
        self.verticalLayout_48.addWidget(self.frame_Calib)
        self.frame_Network = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_Network.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_Network.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_Network.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Network.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Network.setObjectName("frame_Network")
        self.verticalLayout_101 = QtWidgets.QVBoxLayout(self.frame_Network)
        self.verticalLayout_101.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_101.setSpacing(0)
        self.verticalLayout_101.setObjectName("verticalLayout_101")
        self.frame_Network_settings = QtWidgets.QFrame(self.frame_Network)
        self.frame_Network_settings.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_Network_settings.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_Network_settings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Network_settings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Network_settings.setObjectName("frame_Network_settings")
        self.verticalLayout_102 = QtWidgets.QVBoxLayout(self.frame_Network_settings)
        self.verticalLayout_102.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_102.setSpacing(0)
        self.verticalLayout_102.setObjectName("verticalLayout_102")
        self.PB_Audio_Records = QtWidgets.QPushButton(self.frame_Network_settings)
        self.PB_Audio_Records.setMinimumSize(QtCore.QSize(180, 50))
        self.PB_Audio_Records.setMaximumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Audio_Records.setFont(font)
        self.PB_Audio_Records.setStyleSheet("QPushButton{\n"
"border: none;    \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(244, 255, 242);\n"
"}\n"
"QPushButton:focus{\n"
"  background-color: rgb(244, 255, 242);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(244, 255, 242);\n"
"}\n"
"\n"
"\n"
"")
        self.PB_Audio_Records.setIconSize(QtCore.QSize(20, 22))
        self.PB_Audio_Records.setCheckable(True)
        self.PB_Audio_Records.setFlat(True)
        self.PB_Audio_Records.setObjectName("PB_Audio_Records")
        self.verticalLayout_102.addWidget(self.PB_Audio_Records, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_101.addWidget(self.frame_Network_settings, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_48.addWidget(self.frame_Network)
        self.frame_25 = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_report = QtWidgets.QFrame(self.frame_25)
        self.frame_report.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_report.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_report.setObjectName("frame_report")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_report)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_reports = QtWidgets.QFrame(self.frame_report)
        self.frame_reports.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_reports.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_reports.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_reports.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_reports.setObjectName("frame_reports")
        self.verticalLayout_108 = QtWidgets.QVBoxLayout(self.frame_reports)
        self.verticalLayout_108.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_108.setSpacing(0)
        self.verticalLayout_108.setObjectName("verticalLayout_108")
        self.PB_GIS_MAPS = QtWidgets.QPushButton(self.frame_reports)
        self.PB_GIS_MAPS.setMinimumSize(QtCore.QSize(180, 50))
        self.PB_GIS_MAPS.setMaximumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PB_GIS_MAPS.setFont(font)
        self.PB_GIS_MAPS.setStyleSheet("QPushButton{\n"
"border: none;    \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(244, 255, 242);\n"
"}\n"
"QPushButton:focus{\n"
"  background-color: rgb(244, 255, 242);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(244, 255, 242);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.PB_GIS_MAPS.setIconSize(QtCore.QSize(20, 22))
        self.PB_GIS_MAPS.setCheckable(True)
        self.PB_GIS_MAPS.setFlat(True)
        self.PB_GIS_MAPS.setObjectName("PB_GIS_MAPS")
        self.verticalLayout_108.addWidget(self.PB_GIS_MAPS)
        self.verticalLayout_5.addWidget(self.frame_reports)
        self.verticalLayout_18.addWidget(self.frame_report)
        self.frame_reports_menu = QtWidgets.QFrame(self.frame_25)
        self.frame_reports_menu.setStyleSheet("background-color: rgb(226, 233, 255);")
        self.frame_reports_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_reports_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_reports_menu.setObjectName("frame_reports_menu")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.frame_reports_menu)
        self.verticalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.verticalLayout_18.addWidget(self.frame_reports_menu)
        self.verticalLayout_48.addWidget(self.frame_25)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_48.addItem(spacerItem)
        self.frame_History = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_History.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_History.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_History.setObjectName("frame_History")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_History)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_Histy = QtWidgets.QFrame(self.frame_History)
        self.frame_Histy.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_Histy.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_Histy.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Histy.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Histy.setObjectName("frame_Histy")
        self.verticalLayout_111 = QtWidgets.QVBoxLayout(self.frame_Histy)
        self.verticalLayout_111.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_111.setSpacing(0)
        self.verticalLayout_111.setObjectName("verticalLayout_111")
        self.PB_History = QtWidgets.QPushButton(self.frame_Histy)
        self.PB_History.setMinimumSize(QtCore.QSize(180, 50))
        self.PB_History.setMaximumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PB_History.setFont(font)
        self.PB_History.setStyleSheet("QPushButton{\n"
"border: none;    \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(244, 255, 242);\n"
"}\n"
"QPushButton:focus{\n"
"  background-color: rgb(244, 255, 242);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(244, 255, 242);\n"
"}\n"
"\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Resource/icons/history (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_History.setIcon(icon2)
        self.PB_History.setIconSize(QtCore.QSize(30, 30))
        self.PB_History.setFlat(True)
        self.PB_History.setObjectName("PB_History")
        self.verticalLayout_111.addWidget(self.PB_History)
        self.verticalLayout_13.addWidget(self.frame_Histy, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_48.addWidget(self.frame_History)
        self.frame_hel = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_hel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_hel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_hel.setObjectName("frame_hel")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_hel)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_Help = QtWidgets.QFrame(self.frame_hel)
        self.frame_Help.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_Help.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_Help.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Help.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Help.setObjectName("frame_Help")
        self.verticalLayout_105 = QtWidgets.QVBoxLayout(self.frame_Help)
        self.verticalLayout_105.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_105.setSpacing(0)
        self.verticalLayout_105.setObjectName("verticalLayout_105")
        self.PB_Help = QtWidgets.QPushButton(self.frame_Help)
        self.PB_Help.setMinimumSize(QtCore.QSize(180, 50))
        self.PB_Help.setMaximumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Help.setFont(font)
        self.PB_Help.setStyleSheet("QPushButton{\n"
"border: none;    \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(244, 255, 242);\n"
"}\n"
"QPushButton:focus{\n"
"  background-color: rgb(244, 255, 242);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(244, 255, 242);\n"
"}\n"
"\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Resource/icons/icons8-help-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_Help.setIcon(icon3)
        self.PB_Help.setIconSize(QtCore.QSize(30, 30))
        self.PB_Help.setFlat(True)
        self.PB_Help.setObjectName("PB_Help")
        self.verticalLayout_105.addWidget(self.PB_Help, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_7.addWidget(self.frame_Help, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_48.addWidget(self.frame_hel)
        self.frame_us = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_us.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_us.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_us.setObjectName("frame_us")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_us)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_User = QtWidgets.QFrame(self.frame_us)
        self.frame_User.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_User.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_User.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_User.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_User.setObjectName("frame_User")
        self.verticalLayout_103 = QtWidgets.QVBoxLayout(self.frame_User)
        self.verticalLayout_103.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_103.setSpacing(0)
        self.verticalLayout_103.setObjectName("verticalLayout_103")
        self.PB_User = QtWidgets.QPushButton(self.frame_User)
        self.PB_User.setMinimumSize(QtCore.QSize(180, 50))
        self.PB_User.setMaximumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PB_User.setFont(font)
        self.PB_User.setStyleSheet("QPushButton{\n"
"border: none;    \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(244, 255, 242);\n"
"}\n"
"QPushButton:focus{\n"
"  background-color: rgb(244, 255, 242);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(244, 255, 242);\n"
"}\n"
"\n"
"\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Resource/icons/icons8-user-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_User.setIcon(icon4)
        self.PB_User.setIconSize(QtCore.QSize(30, 30))
        self.PB_User.setFlat(True)
        self.PB_User.setObjectName("PB_User")
        self.verticalLayout_103.addWidget(self.PB_User, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_6.addWidget(self.frame_User)
        self.verticalLayout_48.addWidget(self.frame_us)
        self.frame_Logout = QtWidgets.QFrame(self.frame_bottom_west)
        self.frame_Logout.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_Logout.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_Logout.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Logout.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Logout.setObjectName("frame_Logout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_Logout)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_LOGOUT = QtWidgets.QFrame(self.frame_Logout)
        self.frame_LOGOUT.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_LOGOUT.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_LOGOUT.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_LOGOUT.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_LOGOUT.setObjectName("frame_LOGOUT")
        self.verticalLayout_110 = QtWidgets.QVBoxLayout(self.frame_LOGOUT)
        self.verticalLayout_110.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_110.setSpacing(0)
        self.verticalLayout_110.setObjectName("verticalLayout_110")
        self.PB_Logout = QtWidgets.QPushButton(self.frame_LOGOUT)
        self.PB_Logout.setMinimumSize(QtCore.QSize(180, 50))
        self.PB_Logout.setMaximumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PB_Logout.setFont(font)
        self.PB_Logout.setStyleSheet("QPushButton{\n"
"border: none;    \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(244, 255, 242);\n"
"}\n"
"QPushButton:focus{\n"
"  background-color: rgb(244, 255, 242);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(244, 255, 242);\n"
"}\n"
"\n"
"\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Resource/icons/Logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_Logout.setIcon(icon5)
        self.PB_Logout.setIconSize(QtCore.QSize(35, 35))
        self.PB_Logout.setFlat(True)
        self.PB_Logout.setObjectName("PB_Logout")
        self.verticalLayout_110.addWidget(self.PB_Logout, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_8.addWidget(self.frame_LOGOUT, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_48.addWidget(self.frame_Logout)
        self.frame_bottom_east = QtWidgets.QFrame(self.splitter)
        self.frame_bottom_east.setStyleSheet("background-color: rgb(242, 247, 255);")
        self.frame_bottom_east.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bottom_east.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bottom_east.setObjectName("frame_bottom_east")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_bottom_east)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_bottom_east)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_Audio = QtWidgets.QWidget()
        self.page_Audio.setObjectName("page_Audio")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_Audio)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.page_Audio)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_22.addWidget(self.frame_2)
        self.frame_19 = QtWidgets.QFrame(self.frame)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.widget = QtWidgets.QWidget(self.frame_19)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.VE_MusicPlayer = QtWidgets.QVBoxLayout()
        self.VE_MusicPlayer.setObjectName("VE_MusicPlayer")
        self.verticalLayout_21.addLayout(self.VE_MusicPlayer)
        self.horizontalLayout_11.addWidget(self.widget)
        self.frame_18 = QtWidgets.QFrame(self.frame_19)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_16 = QtWidgets.QFrame(self.frame_18)
        self.frame_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_16)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_25.addWidget(self.tableWidget)
        self.textEdit = QtWidgets.QTextEdit(self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_25.addWidget(self.textEdit)
        self.verticalLayout_2.addWidget(self.frame_16)
        self.frame_14 = QtWidgets.QFrame(self.frame_18)
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.PB_Import_Audio_Files = QtWidgets.QPushButton(self.frame_14)
        self.PB_Import_Audio_Files.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Import_Audio_Files.setFont(font)
        self.PB_Import_Audio_Files.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(".\\icons/folder (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_Import_Audio_Files.setIcon(icon6)
        self.PB_Import_Audio_Files.setIconSize(QtCore.QSize(20, 20))
        self.PB_Import_Audio_Files.setObjectName("PB_Import_Audio_Files")
        self.horizontalLayout_7.addWidget(self.PB_Import_Audio_Files)
        self.PB_Play_Audio_to_Text = QtWidgets.QPushButton(self.frame_14)
        self.PB_Play_Audio_to_Text.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Play_Audio_to_Text.setFont(font)
        self.PB_Play_Audio_to_Text.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(".\\icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_Play_Audio_to_Text.setIcon(icon7)
        self.PB_Play_Audio_to_Text.setIconSize(QtCore.QSize(30, 30))
        self.PB_Play_Audio_to_Text.setObjectName("PB_Play_Audio_to_Text")
        self.horizontalLayout_7.addWidget(self.PB_Play_Audio_to_Text)
        self.PB_Save_OCR_To_Word_2 = QtWidgets.QPushButton(self.frame_14)
        self.PB_Save_OCR_To_Word_2.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Save_OCR_To_Word_2.setFont(font)
        self.PB_Save_OCR_To_Word_2.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(".\\icons/word.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_Save_OCR_To_Word_2.setIcon(icon8)
        self.PB_Save_OCR_To_Word_2.setIconSize(QtCore.QSize(30, 30))
        self.PB_Save_OCR_To_Word_2.setObjectName("PB_Save_OCR_To_Word_2")
        self.horizontalLayout_7.addWidget(self.PB_Save_OCR_To_Word_2)
        self.PB_Save_OCR_To_Text_2 = QtWidgets.QPushButton(self.frame_14)
        self.PB_Save_OCR_To_Text_2.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Save_OCR_To_Text_2.setFont(font)
        self.PB_Save_OCR_To_Text_2.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(".\\icons/Notepad.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_Save_OCR_To_Text_2.setIcon(icon9)
        self.PB_Save_OCR_To_Text_2.setIconSize(QtCore.QSize(30, 30))
        self.PB_Save_OCR_To_Text_2.setObjectName("PB_Save_OCR_To_Text_2")
        self.horizontalLayout_7.addWidget(self.PB_Save_OCR_To_Text_2)
        self.verticalLayout_2.addWidget(self.frame_14)
        self.horizontalLayout_11.addWidget(self.frame_18)
        self.verticalLayout_22.addWidget(self.frame_19)
        self.verticalLayout.addWidget(self.frame)
        self.stackedWidget.addWidget(self.page_Audio)
        self.page_OCR_TEXT = QtWidgets.QWidget()
        self.page_OCR_TEXT.setObjectName("page_OCR_TEXT")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.page_OCR_TEXT)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_6 = QtWidgets.QFrame(self.page_OCR_TEXT)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_16.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.splitter_2 = QtWidgets.QSplitter(self.frame_9)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.frame_11 = QtWidgets.QFrame(self.splitter_2)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_11)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_image_ocr = QtWidgets.QWidget()
        self.page_image_ocr.setObjectName("page_image_ocr")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.page_image_ocr)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_OCR_TEXT = QtWidgets.QLabel(self.page_image_ocr)
        self.label_OCR_TEXT.setFrameShape(QtWidgets.QFrame.Box)
        self.label_OCR_TEXT.setText("")
        self.label_OCR_TEXT.setObjectName("label_OCR_TEXT")
        self.verticalLayout_20.addWidget(self.label_OCR_TEXT)
        self.frame_13 = QtWidgets.QFrame(self.page_image_ocr)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_13.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(202, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.PB_Rot_OCR = QtWidgets.QPushButton(self.frame_13)
        self.PB_Rot_OCR.setMinimumSize(QtCore.QSize(0, 25))
        self.PB_Rot_OCR.setMaximumSize(QtCore.QSize(40, 16777215))
        self.PB_Rot_OCR.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Rot_OCR.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(".\\icons/rotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_Rot_OCR.setIcon(icon10)
        self.PB_Rot_OCR.setObjectName("PB_Rot_OCR")
        self.horizontalLayout_2.addWidget(self.PB_Rot_OCR)
        spacerItem2 = QtWidgets.QSpacerItem(201, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_20.addWidget(self.frame_13)
        self.stackedWidget_2.addWidget(self.page_image_ocr)
        self.page_pdf_ocr = QtWidgets.QWidget()
        self.page_pdf_ocr.setObjectName("page_pdf_ocr")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.page_pdf_ocr)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_17 = QtWidgets.QFrame(self.page_pdf_ocr)
        self.frame_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_17.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_OCR_TEXT_PDF = QtWidgets.QLabel(self.frame_17)
        self.label_OCR_TEXT_PDF.setFrameShape(QtWidgets.QFrame.Box)
        self.label_OCR_TEXT_PDF.setText("")
        self.label_OCR_TEXT_PDF.setObjectName("label_OCR_TEXT_PDF")
        self.verticalLayout_23.addWidget(self.label_OCR_TEXT_PDF)
        self.frame_20 = QtWidgets.QFrame(self.frame_17)
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_20.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.PB_Rot_PDF = QtWidgets.QPushButton(self.frame_20)
        self.PB_Rot_PDF.setMinimumSize(QtCore.QSize(0, 25))
        self.PB_Rot_PDF.setMaximumSize(QtCore.QSize(40, 16777215))
        self.PB_Rot_PDF.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Rot_PDF.setText("")
        self.PB_Rot_PDF.setIcon(icon10)
        self.PB_Rot_PDF.setObjectName("PB_Rot_PDF")
        self.horizontalLayout_5.addWidget(self.PB_Rot_PDF)
        self.frame_22 = QtWidgets.QFrame(self.frame_20)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_21 = QtWidgets.QFrame(self.frame_22)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_21.setMaximumSize(QtCore.QSize(80, 16777215))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.frame_21)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.SP_PDF_Page = QtWidgets.QSpinBox(self.frame_21)
        self.SP_PDF_Page.setMinimumSize(QtCore.QSize(50, 0))
        self.SP_PDF_Page.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.SP_PDF_Page.setObjectName("SP_PDF_Page")
        self.horizontalLayout_9.addWidget(self.SP_PDF_Page)
        self.horizontalLayout_8.addWidget(self.frame_21)
        self.PB_PDF_Prev = QtWidgets.QPushButton(self.frame_22)
        self.PB_PDF_Prev.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_PDF_Prev.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(".\\icons/Left-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_PDF_Prev.setIcon(icon11)
        self.PB_PDF_Prev.setObjectName("PB_PDF_Prev")
        self.horizontalLayout_8.addWidget(self.PB_PDF_Prev)
        self.PB_PDF_Next = QtWidgets.QPushButton(self.frame_22)
        self.PB_PDF_Next.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_PDF_Next.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(".\\icons/right-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_PDF_Next.setIcon(icon12)
        self.PB_PDF_Next.setObjectName("PB_PDF_Next")
        self.horizontalLayout_8.addWidget(self.PB_PDF_Next)
        self.horizontalLayout_5.addWidget(self.frame_22)
        spacerItem4 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_23.addWidget(self.frame_20)
        self.verticalLayout_24.addWidget(self.frame_17)
        self.stackedWidget_2.addWidget(self.page_pdf_ocr)
        self.verticalLayout_26.addWidget(self.stackedWidget_2)
        self.frame_12 = QtWidgets.QFrame(self.splitter_2)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.textEdit_OCR_TEXT = QtWidgets.QTextEdit(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.textEdit_OCR_TEXT.setFont(font)
        self.textEdit_OCR_TEXT.setObjectName("textEdit_OCR_TEXT")
        self.verticalLayout_19.addWidget(self.textEdit_OCR_TEXT)
        self.verticalLayout_27.addWidget(self.splitter_2)
        self.verticalLayout_17.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PB_Import_OCR_PDF = QtWidgets.QPushButton(self.frame_10)
        self.PB_Import_OCR_PDF.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Import_OCR_PDF.setFont(font)
        self.PB_Import_OCR_PDF.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Import_OCR_PDF.setIcon(icon6)
        self.PB_Import_OCR_PDF.setIconSize(QtCore.QSize(20, 20))
        self.PB_Import_OCR_PDF.setObjectName("PB_Import_OCR_PDF")
        self.horizontalLayout_3.addWidget(self.PB_Import_OCR_PDF)
        self.PB_Import_OCR = QtWidgets.QPushButton(self.frame_10)
        self.PB_Import_OCR.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Import_OCR.setFont(font)
        self.PB_Import_OCR.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Import_OCR.setIcon(icon6)
        self.PB_Import_OCR.setIconSize(QtCore.QSize(20, 20))
        self.PB_Import_OCR.setObjectName("PB_Import_OCR")
        self.horizontalLayout_3.addWidget(self.PB_Import_OCR)
        self.PB_Rec_Text = QtWidgets.QPushButton(self.frame_10)
        self.PB_Rec_Text.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Rec_Text.setFont(font)
        self.PB_Rec_Text.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(".\\icons/document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_Rec_Text.setIcon(icon13)
        self.PB_Rec_Text.setIconSize(QtCore.QSize(30, 30))
        self.PB_Rec_Text.setObjectName("PB_Rec_Text")
        self.horizontalLayout_3.addWidget(self.PB_Rec_Text)
        self.PB_Play_OCR_Audio = QtWidgets.QPushButton(self.frame_10)
        self.PB_Play_OCR_Audio.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Play_OCR_Audio.setFont(font)
        self.PB_Play_OCR_Audio.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Play_OCR_Audio.setIcon(icon7)
        self.PB_Play_OCR_Audio.setIconSize(QtCore.QSize(30, 30))
        self.PB_Play_OCR_Audio.setObjectName("PB_Play_OCR_Audio")
        self.horizontalLayout_3.addWidget(self.PB_Play_OCR_Audio)
        self.PB_Save_OCR_To_Word = QtWidgets.QPushButton(self.frame_10)
        self.PB_Save_OCR_To_Word.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Save_OCR_To_Word.setFont(font)
        self.PB_Save_OCR_To_Word.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Save_OCR_To_Word.setIcon(icon8)
        self.PB_Save_OCR_To_Word.setIconSize(QtCore.QSize(30, 30))
        self.PB_Save_OCR_To_Word.setObjectName("PB_Save_OCR_To_Word")
        self.horizontalLayout_3.addWidget(self.PB_Save_OCR_To_Word)
        self.PB_Save_OCR_To_Text = QtWidgets.QPushButton(self.frame_10)
        self.PB_Save_OCR_To_Text.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Save_OCR_To_Text.setFont(font)
        self.PB_Save_OCR_To_Text.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Save_OCR_To_Text.setIcon(icon9)
        self.PB_Save_OCR_To_Text.setIconSize(QtCore.QSize(30, 30))
        self.PB_Save_OCR_To_Text.setObjectName("PB_Save_OCR_To_Text")
        self.horizontalLayout_3.addWidget(self.PB_Save_OCR_To_Text)
        self.verticalLayout_17.addWidget(self.frame_10)
        self.verticalLayout_16.addWidget(self.frame_8)
        self.verticalLayout_15.addWidget(self.frame_6)
        self.stackedWidget.addWidget(self.page_OCR_TEXT)
        self.page_GIS_Maps = QtWidgets.QWidget()
        self.page_GIS_Maps.setObjectName("page_GIS_Maps")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.page_GIS_Maps)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.widget_GIS = QtWidgets.QWidget(self.page_GIS_Maps)
        self.widget_GIS.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_GIS.setObjectName("widget_GIS")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.widget_GIS)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.frame_15 = QtWidgets.QFrame(self.widget_GIS)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_6 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_12.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_29.addWidget(self.frame_15)
        self.VE_GISMaps = QtWidgets.QVBoxLayout()
        self.VE_GISMaps.setObjectName("VE_GISMaps")
        self.verticalLayout_29.addLayout(self.VE_GISMaps)
        self.verticalLayout_28.addWidget(self.widget_GIS)
        self.stackedWidget.addWidget(self.page_GIS_Maps)
        self.page_Main = QtWidgets.QWidget()
        self.page_Main.setObjectName("page_Main")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_Main)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.page_Main)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem5 = QtWidgets.QSpacerItem(20, 207, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem5)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\Logo.jpeg"))
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(149, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_9.addWidget(self.frame_5, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_12.addWidget(self.frame_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 207, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem6)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.stackedWidget.addWidget(self.page_Main)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.verticalLayout_14.addWidget(self.splitter)
        self.verticalLayout_61.addWidget(self.frame_bottom)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1188, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.stackedWidget_2.setCurrentIndex(1)
        self.PB_System.toggled['bool'].connect(self.sys_below_frame.setVisible) # type: ignore
        self.PB_System.toggled['bool'].connect(self.sys_below_frame.setHidden) # type: ignore
        self.PB_GIS_MAPS.toggled['bool'].connect(self.frame_reports_menu.setHidden) # type: ignore
        self.PB_GIS_MAPS.toggled['bool'].connect(self.frame_reports_menu.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_System.setText(_translate("MainWindow", "SOCP - Integrated Communications System"))
        self.PB_System.setText(_translate("MainWindow", " System"))
        self.PB_OCR_IMAGE.setText(_translate("MainWindow", "OCR"))
        self.PB_Audio_Records.setText(_translate("MainWindow", "Records"))
        self.PB_GIS_MAPS.setText(_translate("MainWindow", "Maps"))
        self.PB_History.setToolTip(_translate("MainWindow", "History"))
        self.PB_History.setText(_translate("MainWindow", "History"))
        self.PB_Help.setToolTip(_translate("MainWindow", "Help"))
        self.PB_Help.setText(_translate("MainWindow", "Help"))
        self.PB_User.setToolTip(_translate("MainWindow", "User"))
        self.PB_User.setText(_translate("MainWindow", "Account"))
        self.PB_Logout.setToolTip(_translate("MainWindow", "Logout"))
        self.PB_Logout.setText(_translate("MainWindow", "Logout"))
        self.label_4.setText(_translate("MainWindow", "Audio Records Management"))
        self.PB_Import_Audio_Files.setText(_translate("MainWindow", "Import"))
        self.PB_Play_Audio_to_Text.setText(_translate("MainWindow", "Convert"))
        self.PB_Save_OCR_To_Word_2.setText(_translate("MainWindow", "Save"))
        self.PB_Save_OCR_To_Text_2.setText(_translate("MainWindow", "Save"))
        self.label_3.setText(_translate("MainWindow", "OCR Management"))
        self.label_5.setText(_translate("MainWindow", "Page"))
        self.PB_Import_OCR_PDF.setToolTip(_translate("MainWindow", "Import OCR Image File"))
        self.PB_Import_OCR_PDF.setText(_translate("MainWindow", "Import Pdf"))
        self.PB_Import_OCR.setToolTip(_translate("MainWindow", "Import OCR Image File"))
        self.PB_Import_OCR.setText(_translate("MainWindow", "Import Image"))
        self.PB_Rec_Text.setText(_translate("MainWindow", "Recognise Text"))
        self.PB_Play_OCR_Audio.setText(_translate("MainWindow", "Play Audio"))
        self.PB_Save_OCR_To_Word.setText(_translate("MainWindow", "Save"))
        self.PB_Save_OCR_To_Text.setText(_translate("MainWindow", "Save"))
        self.label_6.setText(_translate("MainWindow", "Geo Information System Maps"))
        self.label_2.setText(_translate("MainWindow", "Aniketa Advanced Systems Pvt Limited,\n"
"              Hyderabad - 500005"))
import Resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
