# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1222, 852)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_13.setSpacing(2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.frame_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(2)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.GB_System = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.GB_System.setFont(font)
        self.GB_System.setObjectName("GB_System")
        self.gridLayout = QtWidgets.QGridLayout(self.GB_System)
        self.gridLayout.setObjectName("gridLayout")
        self.PB_System = QtWidgets.QPushButton(self.GB_System)
        self.PB_System.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_System.setFont(font)
        self.PB_System.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_System.setObjectName("PB_System")
        self.gridLayout.addWidget(self.PB_System, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.GB_System)
        self.GB_Subsystem = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.GB_Subsystem.setFont(font)
        self.GB_Subsystem.setObjectName("GB_Subsystem")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.GB_Subsystem)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.PB_Subsystem = QtWidgets.QPushButton(self.GB_Subsystem)
        self.PB_Subsystem.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Subsystem.setFont(font)
        self.PB_Subsystem.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Subsystem.setObjectName("PB_Subsystem")
        self.gridLayout_2.addWidget(self.PB_Subsystem, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.GB_Subsystem)
        self.GB_Standardtestequipment = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.GB_Standardtestequipment.setFont(font)
        self.GB_Standardtestequipment.setObjectName("GB_Standardtestequipment")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.GB_Standardtestequipment)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PB_SSG = QtWidgets.QPushButton(self.GB_Standardtestequipment)
        self.PB_SSG.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_SSG.setFont(font)
        self.PB_SSG.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_SSG.setObjectName("PB_SSG")
        self.gridLayout_3.addWidget(self.PB_SSG, 0, 0, 1, 1)
        self.PB_SA = QtWidgets.QPushButton(self.GB_Standardtestequipment)
        self.PB_SA.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_SA.setFont(font)
        self.PB_SA.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_SA.setObjectName("PB_SA")
        self.gridLayout_3.addWidget(self.PB_SA, 0, 1, 1, 1)
        self.PB_NA = QtWidgets.QPushButton(self.GB_Standardtestequipment)
        self.PB_NA.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_NA.setFont(font)
        self.PB_NA.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_NA.setObjectName("PB_NA")
        self.gridLayout_3.addWidget(self.PB_NA, 1, 0, 1, 1)
        self.PB_VSG = QtWidgets.QPushButton(self.GB_Standardtestequipment)
        self.PB_VSG.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_VSG.setFont(font)
        self.PB_VSG.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_VSG.setObjectName("PB_VSG")
        self.gridLayout_3.addWidget(self.PB_VSG, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.GB_Standardtestequipment)
        self.GB_Specialtestequipment = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.GB_Specialtestequipment.setFont(font)
        self.GB_Specialtestequipment.setObjectName("GB_Specialtestequipment")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.GB_Specialtestequipment)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.PB_Poweramplifier = QtWidgets.QPushButton(self.GB_Specialtestequipment)
        self.PB_Poweramplifier.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Poweramplifier.setFont(font)
        self.PB_Poweramplifier.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Poweramplifier.setObjectName("PB_Poweramplifier")
        self.gridLayout_4.addWidget(self.PB_Poweramplifier, 0, 0, 1, 1)
        self.PB_Powersupplyunit = QtWidgets.QPushButton(self.GB_Specialtestequipment)
        self.PB_Powersupplyunit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Powersupplyunit.setFont(font)
        self.PB_Powersupplyunit.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Powersupplyunit.setObjectName("PB_Powersupplyunit")
        self.gridLayout_4.addWidget(self.PB_Powersupplyunit, 0, 1, 1, 1)
        self.PB_Spectrumanalyzer = QtWidgets.QPushButton(self.GB_Specialtestequipment)
        self.PB_Spectrumanalyzer.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Spectrumanalyzer.setFont(font)
        self.PB_Spectrumanalyzer.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Spectrumanalyzer.setObjectName("PB_Spectrumanalyzer")
        self.gridLayout_4.addWidget(self.PB_Spectrumanalyzer, 1, 0, 1, 1)
        self.PB_Testjig = QtWidgets.QPushButton(self.GB_Specialtestequipment)
        self.PB_Testjig.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Testjig.setFont(font)
        self.PB_Testjig.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Testjig.setObjectName("PB_Testjig")
        self.gridLayout_4.addWidget(self.PB_Testjig, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.GB_Specialtestequipment)
        self.GB_Database = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.GB_Database.setFont(font)
        self.GB_Database.setObjectName("GB_Database")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.GB_Database)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.PB_Database = QtWidgets.QPushButton(self.GB_Database)
        self.PB_Database.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Database.setFont(font)
        self.PB_Database.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Database.setObjectName("PB_Database")
        self.gridLayout_5.addWidget(self.PB_Database, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.GB_Database)
        self.GB_Filepaths = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.GB_Filepaths.setFont(font)
        self.GB_Filepaths.setObjectName("GB_Filepaths")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.GB_Filepaths)
        self.gridLayout_6.setHorizontalSpacing(11)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.PB_Filepath = QtWidgets.QPushButton(self.GB_Filepaths)
        self.PB_Filepath.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Filepath.setFont(font)
        self.PB_Filepath.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Filepath.setObjectName("PB_Filepath")
        self.gridLayout_6.addWidget(self.PB_Filepath, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.GB_Filepaths)
        self.frame_3 = QtWidgets.QFrame(self.splitter)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.stackedWidget.setFont(font)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.SW_System = QtWidgets.QWidget()
        self.SW_System.setObjectName("SW_System")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.SW_System)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.SW_System)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.SW_System)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_4)
        self.tableWidget.setLineWidth(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.SW_System)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PB_New_3 = QtWidgets.QPushButton(self.frame_6)
        self.PB_New_3.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_New_3.setFont(font)
        self.PB_New_3.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_New_3.setObjectName("PB_New_3")
        self.horizontalLayout_2.addWidget(self.PB_New_3)
        self.PB_Delete_3 = QtWidgets.QPushButton(self.frame_6)
        self.PB_Delete_3.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Delete_3.setFont(font)
        self.PB_Delete_3.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Delete_3.setObjectName("PB_Delete_3")
        self.horizontalLayout_2.addWidget(self.PB_Delete_3)
        self.PB_Save_4 = QtWidgets.QPushButton(self.frame_6)
        self.PB_Save_4.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Save_4.setFont(font)
        self.PB_Save_4.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Save_4.setObjectName("PB_Save_4")
        self.horizontalLayout_2.addWidget(self.PB_Save_4)
        self.PB_Export_3 = QtWidgets.QPushButton(self.frame_6)
        self.PB_Export_3.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Export_3.setFont(font)
        self.PB_Export_3.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Export_3.setObjectName("PB_Export_3")
        self.horizontalLayout_2.addWidget(self.PB_Export_3)
        self.PB_Close_3 = QtWidgets.QPushButton(self.frame_6)
        self.PB_Close_3.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Close_3.setFont(font)
        self.PB_Close_3.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Close_3.setObjectName("PB_Close_3")
        self.horizontalLayout_2.addWidget(self.PB_Close_3)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.stackedWidget.addWidget(self.SW_System)
        self.SW_FilePath = QtWidgets.QWidget()
        self.SW_FilePath.setObjectName("SW_FilePath")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.SW_FilePath)
        self.verticalLayout_15.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_14 = QtWidgets.QFrame(self.SW_FilePath)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 53))
        self.frame_14.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_17.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_17.setSpacing(2)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_4 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_17.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_15.addWidget(self.frame_14)
        self.frame_17 = QtWidgets.QFrame(self.SW_FilePath)
        self.frame_17.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_9.setContentsMargins(2, 2, 2, -1)
        self.gridLayout_9.setSpacing(2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.GB_Rwr = QtWidgets.QGroupBox(self.frame_17)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.GB_Rwr.setFont(font)
        self.GB_Rwr.setObjectName("GB_Rwr")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.GB_Rwr)
        self.gridLayout_8.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_8.setSpacing(2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_27 = QtWidgets.QFrame(self.GB_Rwr)
        self.frame_27.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_20.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_5 = QtWidgets.QLabel(self.frame_27)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_20.addWidget(self.label_5)
        self.LE_Inputdatafiles = QtWidgets.QLineEdit(self.frame_27)
        self.LE_Inputdatafiles.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LE_Inputdatafiles.setFont(font)
        self.LE_Inputdatafiles.setObjectName("LE_Inputdatafiles")
        self.verticalLayout_20.addWidget(self.LE_Inputdatafiles)
        self.gridLayout_8.addWidget(self.frame_27, 0, 0, 1, 1)
        self.frame_28 = QtWidgets.QFrame(self.GB_Rwr)
        self.frame_28.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_24.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_6 = QtWidgets.QLabel(self.frame_28)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_24.addWidget(self.label_6)
        self.LE_Reportfiles = QtWidgets.QLineEdit(self.frame_28)
        self.LE_Reportfiles.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LE_Reportfiles.setFont(font)
        self.LE_Reportfiles.setObjectName("LE_Reportfiles")
        self.verticalLayout_24.addWidget(self.LE_Reportfiles)
        self.gridLayout_8.addWidget(self.frame_28, 0, 1, 1, 1)
        self.frame_29 = QtWidgets.QFrame(self.GB_Rwr)
        self.frame_29.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.PB_Save_6 = QtWidgets.QPushButton(self.frame_29)
        self.PB_Save_6.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Save_6.setFont(font)
        self.PB_Save_6.setObjectName("PB_Save_6")
        self.horizontalLayout_6.addWidget(self.PB_Save_6)
        self.PB_Get_3 = QtWidgets.QPushButton(self.frame_29)
        self.PB_Get_3.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Get_3.setFont(font)
        self.PB_Get_3.setObjectName("PB_Get_3")
        self.horizontalLayout_6.addWidget(self.PB_Get_3)
        self.PB_Refresh_3 = QtWidgets.QPushButton(self.frame_29)
        self.PB_Refresh_3.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Refresh_3.setFont(font)
        self.PB_Refresh_3.setObjectName("PB_Refresh_3")
        self.horizontalLayout_6.addWidget(self.PB_Refresh_3)
        self.gridLayout_8.addWidget(self.frame_29, 1, 0, 1, 2)
        self.gridLayout_9.addWidget(self.GB_Rwr, 2, 0, 1, 1)
        self.GB_Esmp = QtWidgets.QGroupBox(self.frame_17)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.GB_Esmp.setFont(font)
        self.GB_Esmp.setObjectName("GB_Esmp")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.GB_Esmp)
        self.gridLayout_10.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_10.setSpacing(2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frame_30 = QtWidgets.QFrame(self.GB_Esmp)
        self.frame_30.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_26.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_7 = QtWidgets.QLabel(self.frame_30)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_26.addWidget(self.label_7)
        self.LE_Inputdatafiles_2 = QtWidgets.QLineEdit(self.frame_30)
        self.LE_Inputdatafiles_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LE_Inputdatafiles_2.setFont(font)
        self.LE_Inputdatafiles_2.setObjectName("LE_Inputdatafiles_2")
        self.verticalLayout_26.addWidget(self.LE_Inputdatafiles_2)
        self.gridLayout_10.addWidget(self.frame_30, 0, 0, 1, 1)
        self.frame_31 = QtWidgets.QFrame(self.GB_Esmp)
        self.frame_31.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_27.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_9 = QtWidgets.QLabel(self.frame_31)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_27.addWidget(self.label_9)
        self.LE_Reportfiles_2 = QtWidgets.QLineEdit(self.frame_31)
        self.LE_Reportfiles_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LE_Reportfiles_2.setFont(font)
        self.LE_Reportfiles_2.setObjectName("LE_Reportfiles_2")
        self.verticalLayout_27.addWidget(self.LE_Reportfiles_2)
        self.gridLayout_10.addWidget(self.frame_31, 0, 1, 1, 1)
        self.frame_32 = QtWidgets.QFrame(self.GB_Esmp)
        self.frame_32.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.PB_Save_7 = QtWidgets.QPushButton(self.frame_32)
        self.PB_Save_7.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Save_7.setFont(font)
        self.PB_Save_7.setObjectName("PB_Save_7")
        self.horizontalLayout_7.addWidget(self.PB_Save_7)
        self.PB_Get_4 = QtWidgets.QPushButton(self.frame_32)
        self.PB_Get_4.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Get_4.setFont(font)
        self.PB_Get_4.setObjectName("PB_Get_4")
        self.horizontalLayout_7.addWidget(self.PB_Get_4)
        self.PB_Refresh_4 = QtWidgets.QPushButton(self.frame_32)
        self.PB_Refresh_4.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Refresh_4.setFont(font)
        self.PB_Refresh_4.setObjectName("PB_Refresh_4")
        self.horizontalLayout_7.addWidget(self.PB_Refresh_4)
        self.gridLayout_10.addWidget(self.frame_32, 1, 0, 1, 2)
        self.gridLayout_9.addWidget(self.GB_Esmp, 3, 0, 1, 1)
        self.GB_Rfps = QtWidgets.QGroupBox(self.frame_17)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.GB_Rfps.setFont(font)
        self.GB_Rfps.setObjectName("GB_Rfps")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.GB_Rfps)
        self.gridLayout_11.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_11.setSpacing(2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frame_33 = QtWidgets.QFrame(self.GB_Rfps)
        self.frame_33.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_29.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_10 = QtWidgets.QLabel(self.frame_33)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_29.addWidget(self.label_10)
        self.LE_Inputdatafiles_3 = QtWidgets.QLineEdit(self.frame_33)
        self.LE_Inputdatafiles_3.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LE_Inputdatafiles_3.setFont(font)
        self.LE_Inputdatafiles_3.setObjectName("LE_Inputdatafiles_3")
        self.verticalLayout_29.addWidget(self.LE_Inputdatafiles_3)
        self.gridLayout_11.addWidget(self.frame_33, 0, 0, 1, 1)
        self.frame_34 = QtWidgets.QFrame(self.GB_Rfps)
        self.frame_34.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_34)
        self.verticalLayout_30.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_11 = QtWidgets.QLabel(self.frame_34)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_30.addWidget(self.label_11)
        self.LE_Reportfiles_3 = QtWidgets.QLineEdit(self.frame_34)
        self.LE_Reportfiles_3.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LE_Reportfiles_3.setFont(font)
        self.LE_Reportfiles_3.setObjectName("LE_Reportfiles_3")
        self.verticalLayout_30.addWidget(self.LE_Reportfiles_3)
        self.gridLayout_11.addWidget(self.frame_34, 0, 1, 1, 1)
        self.frame_35 = QtWidgets.QFrame(self.GB_Rfps)
        self.frame_35.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.PB_Save_8 = QtWidgets.QPushButton(self.frame_35)
        self.PB_Save_8.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Save_8.setFont(font)
        self.PB_Save_8.setObjectName("PB_Save_8")
        self.horizontalLayout_8.addWidget(self.PB_Save_8)
        self.PB_Get_5 = QtWidgets.QPushButton(self.frame_35)
        self.PB_Get_5.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Get_5.setFont(font)
        self.PB_Get_5.setObjectName("PB_Get_5")
        self.horizontalLayout_8.addWidget(self.PB_Get_5)
        self.PB_Refresh_5 = QtWidgets.QPushButton(self.frame_35)
        self.PB_Refresh_5.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Refresh_5.setFont(font)
        self.PB_Refresh_5.setObjectName("PB_Refresh_5")
        self.horizontalLayout_8.addWidget(self.PB_Refresh_5)
        self.gridLayout_11.addWidget(self.frame_35, 1, 0, 1, 2)
        self.gridLayout_9.addWidget(self.GB_Rfps, 4, 0, 1, 1)
        self.GB_Pathloss = QtWidgets.QGroupBox(self.frame_17)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.GB_Pathloss.setFont(font)
        self.GB_Pathloss.setObjectName("GB_Pathloss")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.GB_Pathloss)
        self.gridLayout_7.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_7.setSpacing(2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_16 = QtWidgets.QFrame(self.GB_Pathloss)
        self.frame_16.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_19.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_16 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_19.addWidget(self.label_16)
        self.LE_Cableloss = QtWidgets.QLineEdit(self.frame_16)
        self.LE_Cableloss.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LE_Cableloss.setFont(font)
        self.LE_Cableloss.setObjectName("LE_Cableloss")
        self.verticalLayout_19.addWidget(self.LE_Cableloss)
        self.gridLayout_7.addWidget(self.frame_16, 0, 1, 2, 1)
        self.frame_25 = QtWidgets.QFrame(self.GB_Pathloss)
        self.frame_25.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_22.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_18 = QtWidgets.QLabel(self.frame_25)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_22.addWidget(self.label_18)
        self.LE_Txantenna = QtWidgets.QLineEdit(self.frame_25)
        self.LE_Txantenna.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LE_Txantenna.setFont(font)
        self.LE_Txantenna.setObjectName("LE_Txantenna")
        self.verticalLayout_22.addWidget(self.LE_Txantenna)
        self.gridLayout_7.addWidget(self.frame_25, 2, 1, 1, 1)
        self.frame_15 = QtWidgets.QFrame(self.GB_Pathloss)
        self.frame_15.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_18.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_15 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_18.addWidget(self.label_15)
        self.LE_Profiles = QtWidgets.QLineEdit(self.frame_15)
        self.LE_Profiles.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LE_Profiles.setFont(font)
        self.LE_Profiles.setObjectName("LE_Profiles")
        self.verticalLayout_18.addWidget(self.LE_Profiles)
        self.gridLayout_7.addWidget(self.frame_15, 0, 0, 1, 1)
        self.frame_19 = QtWidgets.QFrame(self.GB_Pathloss)
        self.frame_19.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_21.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_17 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_21.addWidget(self.label_17)
        self.LE_Poweramplitude = QtWidgets.QLineEdit(self.frame_19)
        self.LE_Poweramplitude.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LE_Poweramplitude.setFont(font)
        self.LE_Poweramplitude.setObjectName("LE_Poweramplitude")
        self.verticalLayout_21.addWidget(self.LE_Poweramplitude)
        self.gridLayout_7.addWidget(self.frame_19, 1, 0, 2, 1)
        self.frame_26 = QtWidgets.QFrame(self.GB_Pathloss)
        self.frame_26.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.PB_Save_5 = QtWidgets.QPushButton(self.frame_26)
        self.PB_Save_5.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Save_5.setFont(font)
        self.PB_Save_5.setObjectName("PB_Save_5")
        self.horizontalLayout_5.addWidget(self.PB_Save_5)
        self.PB_Get_2 = QtWidgets.QPushButton(self.frame_26)
        self.PB_Get_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Get_2.setFont(font)
        self.PB_Get_2.setObjectName("PB_Get_2")
        self.horizontalLayout_5.addWidget(self.PB_Get_2)
        self.PB_Refresh_2 = QtWidgets.QPushButton(self.frame_26)
        self.PB_Refresh_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Refresh_2.setFont(font)
        self.PB_Refresh_2.setObjectName("PB_Refresh_2")
        self.horizontalLayout_5.addWidget(self.PB_Refresh_2)
        self.gridLayout_7.addWidget(self.frame_26, 3, 0, 1, 2)
        self.gridLayout_9.addWidget(self.GB_Pathloss, 0, 0, 1, 1)
        self.GB_Warner = QtWidgets.QGroupBox(self.frame_17)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.GB_Warner.setFont(font)
        self.GB_Warner.setObjectName("GB_Warner")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.GB_Warner)
        self.gridLayout_12.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_12.setSpacing(2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frame_36 = QtWidgets.QFrame(self.GB_Warner)
        self.frame_36.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_36)
        self.verticalLayout_32.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_12 = QtWidgets.QLabel(self.frame_36)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_32.addWidget(self.label_12)
        self.LE_Inputdatafiles_4 = QtWidgets.QLineEdit(self.frame_36)
        self.LE_Inputdatafiles_4.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LE_Inputdatafiles_4.setFont(font)
        self.LE_Inputdatafiles_4.setObjectName("LE_Inputdatafiles_4")
        self.verticalLayout_32.addWidget(self.LE_Inputdatafiles_4)
        self.gridLayout_12.addWidget(self.frame_36, 0, 0, 1, 1)
        self.frame_37 = QtWidgets.QFrame(self.GB_Warner)
        self.frame_37.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.frame_37)
        self.verticalLayout_33.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_13 = QtWidgets.QLabel(self.frame_37)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_33.addWidget(self.label_13)
        self.LE_Reportfiles_4 = QtWidgets.QLineEdit(self.frame_37)
        self.LE_Reportfiles_4.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LE_Reportfiles_4.setFont(font)
        self.LE_Reportfiles_4.setObjectName("LE_Reportfiles_4")
        self.verticalLayout_33.addWidget(self.LE_Reportfiles_4)
        self.gridLayout_12.addWidget(self.frame_37, 0, 1, 1, 1)
        self.frame_38 = QtWidgets.QFrame(self.GB_Warner)
        self.frame_38.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_38)
        self.horizontalLayout_9.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.PB_Save_9 = QtWidgets.QPushButton(self.frame_38)
        self.PB_Save_9.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Save_9.setFont(font)
        self.PB_Save_9.setObjectName("PB_Save_9")
        self.horizontalLayout_9.addWidget(self.PB_Save_9)
        self.PB_Get_6 = QtWidgets.QPushButton(self.frame_38)
        self.PB_Get_6.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Get_6.setFont(font)
        self.PB_Get_6.setObjectName("PB_Get_6")
        self.horizontalLayout_9.addWidget(self.PB_Get_6)
        self.PB_Refresh_6 = QtWidgets.QPushButton(self.frame_38)
        self.PB_Refresh_6.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Refresh_6.setFont(font)
        self.PB_Refresh_6.setObjectName("PB_Refresh_6")
        self.horizontalLayout_9.addWidget(self.PB_Refresh_6)
        self.gridLayout_12.addWidget(self.frame_38, 1, 0, 1, 2)
        self.gridLayout_9.addWidget(self.GB_Warner, 5, 0, 1, 1)
        self.verticalLayout_15.addWidget(self.frame_17)
        self.stackedWidget.addWidget(self.SW_FilePath)
        self.SW_DataBase = QtWidgets.QWidget()
        self.SW_DataBase.setObjectName("SW_DataBase")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.SW_DataBase)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_18 = QtWidgets.QFrame(self.SW_DataBase)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_18.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_8 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_35.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_14.addWidget(self.frame_18, 0, QtCore.Qt.AlignTop)
        self.frame_20 = QtWidgets.QFrame(self.SW_DataBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_20.sizePolicy().hasHeightForWidth())
        self.frame_20.setSizePolicy(sizePolicy)
        self.frame_20.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_38.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.frame_20)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.verticalLayout_38.addWidget(self.tableWidget_4)
        self.frame_22 = QtWidgets.QFrame(self.frame_20)
        self.frame_22.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PB_Save = QtWidgets.QPushButton(self.frame_22)
        self.PB_Save.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Save.setFont(font)
        self.PB_Save.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Save.setObjectName("PB_Save")
        self.horizontalLayout.addWidget(self.PB_Save)
        self.PB_Get = QtWidgets.QPushButton(self.frame_22)
        self.PB_Get.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Get.setFont(font)
        self.PB_Get.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Get.setObjectName("PB_Get")
        self.horizontalLayout.addWidget(self.PB_Get)
        self.PB_Refresh = QtWidgets.QPushButton(self.frame_22)
        self.PB_Refresh.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.PB_Refresh.setFont(font)
        self.PB_Refresh.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Refresh.setObjectName("PB_Refresh")
        self.horizontalLayout.addWidget(self.PB_Refresh)
        self.verticalLayout_38.addWidget(self.frame_22)
        self.frame_23 = QtWidgets.QFrame(self.frame_20)
        self.frame_23.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_23)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_14 = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_13.addWidget(self.label_14, 0, 0, 1, 1)
        self.LE_Host = QtWidgets.QLineEdit(self.frame_23)
        self.LE_Host.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.LE_Host.setFont(font)
        self.LE_Host.setObjectName("LE_Host")
        self.gridLayout_13.addWidget(self.LE_Host, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_13.addWidget(self.label_19, 1, 0, 1, 1)
        self.LE_Port = QtWidgets.QLineEdit(self.frame_23)
        self.LE_Port.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.LE_Port.setFont(font)
        self.LE_Port.setObjectName("LE_Port")
        self.gridLayout_13.addWidget(self.LE_Port, 1, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_13.addWidget(self.label_20, 2, 0, 1, 1)
        self.LE_Database = QtWidgets.QLineEdit(self.frame_23)
        self.LE_Database.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.LE_Database.setFont(font)
        self.LE_Database.setObjectName("LE_Database")
        self.gridLayout_13.addWidget(self.LE_Database, 2, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_13.addWidget(self.label_21, 3, 0, 1, 1)
        self.LE_Username = QtWidgets.QLineEdit(self.frame_23)
        self.LE_Username.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.LE_Username.setFont(font)
        self.LE_Username.setObjectName("LE_Username")
        self.gridLayout_13.addWidget(self.LE_Username, 3, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_23)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_13.addWidget(self.label_22, 4, 0, 1, 1)
        self.LE_Password = QtWidgets.QLineEdit(self.frame_23)
        self.LE_Password.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.LE_Password.setFont(font)
        self.LE_Password.setObjectName("LE_Password")
        self.gridLayout_13.addWidget(self.LE_Password, 4, 1, 1, 1)
        self.verticalLayout_38.addWidget(self.frame_23)
        self.verticalLayout_14.addWidget(self.frame_20)
        self.stackedWidget.addWidget(self.SW_DataBase)
        self.SW_SubSystem = QtWidgets.QWidget()
        self.SW_SubSystem.setObjectName("SW_SubSystem")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.SW_SubSystem)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_8 = QtWidgets.QFrame(self.SW_SubSystem)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_9.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.SW_SubSystem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_7)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.verticalLayout_7.addWidget(self.tableWidget_2)
        self.verticalLayout_9.addWidget(self.frame_7)
        self.frame_9 = QtWidgets.QFrame(self.SW_SubSystem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PB_New = QtWidgets.QPushButton(self.frame_9)
        self.PB_New.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_New.setFont(font)
        self.PB_New.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_New.setObjectName("PB_New")
        self.horizontalLayout_3.addWidget(self.PB_New)
        self.PB_Delete = QtWidgets.QPushButton(self.frame_9)
        self.PB_Delete.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Delete.setFont(font)
        self.PB_Delete.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Delete.setObjectName("PB_Delete")
        self.horizontalLayout_3.addWidget(self.PB_Delete)
        self.PB_Save_2 = QtWidgets.QPushButton(self.frame_9)
        self.PB_Save_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Save_2.setFont(font)
        self.PB_Save_2.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Save_2.setObjectName("PB_Save_2")
        self.horizontalLayout_3.addWidget(self.PB_Save_2)
        self.PB_Export = QtWidgets.QPushButton(self.frame_9)
        self.PB_Export.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Export.setFont(font)
        self.PB_Export.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Export.setObjectName("PB_Export")
        self.horizontalLayout_3.addWidget(self.PB_Export)
        self.PB_Close = QtWidgets.QPushButton(self.frame_9)
        self.PB_Close.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Close.setFont(font)
        self.PB_Close.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Close.setObjectName("PB_Close")
        self.horizontalLayout_3.addWidget(self.PB_Close)
        self.verticalLayout_9.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.SW_SubSystem)
        self.SW_SSG = QtWidgets.QWidget()
        self.SW_SSG.setObjectName("SW_SSG")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.SW_SSG)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_11 = QtWidgets.QFrame(self.SW_SSG)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_11.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_12.addWidget(self.frame_11)
        self.frame_10 = QtWidgets.QFrame(self.SW_SSG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_10.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.frame_10)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(4)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        self.verticalLayout_10.addWidget(self.tableWidget_3)
        self.verticalLayout_12.addWidget(self.frame_10)
        self.frame_12 = QtWidgets.QFrame(self.SW_SSG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_12.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.PB_New_2 = QtWidgets.QPushButton(self.frame_12)
        self.PB_New_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_New_2.setFont(font)
        self.PB_New_2.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_New_2.setObjectName("PB_New_2")
        self.horizontalLayout_4.addWidget(self.PB_New_2)
        self.PB_Delete_2 = QtWidgets.QPushButton(self.frame_12)
        self.PB_Delete_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Delete_2.setFont(font)
        self.PB_Delete_2.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Delete_2.setObjectName("PB_Delete_2")
        self.horizontalLayout_4.addWidget(self.PB_Delete_2)
        self.PB_Save_3 = QtWidgets.QPushButton(self.frame_12)
        self.PB_Save_3.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Save_3.setFont(font)
        self.PB_Save_3.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Save_3.setObjectName("PB_Save_3")
        self.horizontalLayout_4.addWidget(self.PB_Save_3)
        self.PB_Export_2 = QtWidgets.QPushButton(self.frame_12)
        self.PB_Export_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Export_2.setFont(font)
        self.PB_Export_2.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Export_2.setObjectName("PB_Export_2")
        self.horizontalLayout_4.addWidget(self.PB_Export_2)
        self.PB_Close_2 = QtWidgets.QPushButton(self.frame_12)
        self.PB_Close_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PB_Close_2.setFont(font)
        self.PB_Close_2.setStyleSheet("QPushButton\n"
"                    {\n"
"                       border: 1px solid rgb(0,0,160);    \n"
"                     border-radius : 6px;\n"
"    background-color: rgb(255, 255, 255);\n"
"                        \n"
"                    }\n"
"                      QPushButton:hover{\n"
"            \n"
"                     background-color:  rgb(246, 255, 187);\n"
"                                      \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color :rgb(246, 255, 187);\n"
"}\n"
"")
        self.PB_Close_2.setObjectName("PB_Close_2")
        self.horizontalLayout_4.addWidget(self.PB_Close_2)
        self.verticalLayout_12.addWidget(self.frame_12)
        self.stackedWidget.addWidget(self.SW_SSG)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.splitter)
        self.verticalLayout_13.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GB_System.setTitle(_translate("MainWindow", "System"))
        self.PB_System.setText(_translate("MainWindow", "System"))
        self.GB_Subsystem.setTitle(_translate("MainWindow", "Sub System"))
        self.PB_Subsystem.setText(_translate("MainWindow", "Sub System"))
        self.GB_Standardtestequipment.setTitle(_translate("MainWindow", "Standard Test Equipment"))
        self.PB_SSG.setText(_translate("MainWindow", "SSG"))
        self.PB_SA.setText(_translate("MainWindow", "SA"))
        self.PB_NA.setText(_translate("MainWindow", "NA"))
        self.PB_VSG.setText(_translate("MainWindow", "VSG"))
        self.GB_Specialtestequipment.setTitle(_translate("MainWindow", "Special Test Equipment"))
        self.PB_Poweramplifier.setText(_translate("MainWindow", "Power Amplifier"))
        self.PB_Powersupplyunit.setText(_translate("MainWindow", "Power Supply Unit"))
        self.PB_Spectrumanalyzer.setText(_translate("MainWindow", "Spectrum Analyzer"))
        self.PB_Testjig.setText(_translate("MainWindow", "Test Jig"))
        self.GB_Database.setTitle(_translate("MainWindow", "DataBase"))
        self.PB_Database.setText(_translate("MainWindow", "DataBase"))
        self.GB_Filepaths.setTitle(_translate("MainWindow", "FilePaths"))
        self.PB_Filepath.setText(_translate("MainWindow", "FilePath"))
        self.label.setText(_translate("MainWindow", "System"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IP Address"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Port"))
        self.PB_New_3.setText(_translate("MainWindow", "New"))
        self.PB_Delete_3.setText(_translate("MainWindow", "Delete"))
        self.PB_Save_4.setText(_translate("MainWindow", "Save"))
        self.PB_Export_3.setText(_translate("MainWindow", "Export"))
        self.PB_Close_3.setText(_translate("MainWindow", "Close"))
        self.label_4.setText(_translate("MainWindow", "File Path"))
        self.GB_Rwr.setTitle(_translate("MainWindow", "RWR"))
        self.label_5.setText(_translate("MainWindow", "Input Data Files"))
        self.label_6.setText(_translate("MainWindow", "Report Files"))
        self.PB_Save_6.setText(_translate("MainWindow", "Save"))
        self.PB_Get_3.setText(_translate("MainWindow", "Get"))
        self.PB_Refresh_3.setText(_translate("MainWindow", "Refresh"))
        self.GB_Esmp.setTitle(_translate("MainWindow", "ESMP"))
        self.label_7.setText(_translate("MainWindow", "Input Data Files"))
        self.label_9.setText(_translate("MainWindow", "Report Files"))
        self.PB_Save_7.setText(_translate("MainWindow", "Save"))
        self.PB_Get_4.setText(_translate("MainWindow", "Get"))
        self.PB_Refresh_4.setText(_translate("MainWindow", "Refresh"))
        self.GB_Rfps.setTitle(_translate("MainWindow", "RFPS"))
        self.label_10.setText(_translate("MainWindow", "Input Data Files"))
        self.label_11.setText(_translate("MainWindow", "Report Files"))
        self.PB_Save_8.setText(_translate("MainWindow", "Save"))
        self.PB_Get_5.setText(_translate("MainWindow", "Get"))
        self.PB_Refresh_5.setText(_translate("MainWindow", "Refresh"))
        self.GB_Pathloss.setTitle(_translate("MainWindow", "Path Loss"))
        self.label_16.setText(_translate("MainWindow", "Cable Loss"))
        self.label_18.setText(_translate("MainWindow", "Tx Antenna"))
        self.label_15.setText(_translate("MainWindow", "Profiles"))
        self.label_17.setText(_translate("MainWindow", "Power Amplitude"))
        self.PB_Save_5.setText(_translate("MainWindow", "Save"))
        self.PB_Get_2.setText(_translate("MainWindow", "Get"))
        self.PB_Refresh_2.setText(_translate("MainWindow", "Refresh"))
        self.GB_Warner.setTitle(_translate("MainWindow", "Warner"))
        self.label_12.setText(_translate("MainWindow", "Input Data Files"))
        self.label_13.setText(_translate("MainWindow", "Report Files"))
        self.PB_Save_9.setText(_translate("MainWindow", "Save"))
        self.PB_Get_6.setText(_translate("MainWindow", "Get"))
        self.PB_Refresh_6.setText(_translate("MainWindow", "Refresh"))
        self.label_8.setText(_translate("MainWindow", "Database"))
        self.PB_Save.setText(_translate("MainWindow", "Save"))
        self.PB_Get.setText(_translate("MainWindow", "Get"))
        self.PB_Refresh.setText(_translate("MainWindow", "Refresh"))
        self.label_14.setText(_translate("MainWindow", "Host"))
        self.label_19.setText(_translate("MainWindow", "Port"))
        self.label_20.setText(_translate("MainWindow", "DataBase"))
        self.label_21.setText(_translate("MainWindow", "User Name"))
        self.label_22.setText(_translate("MainWindow", "Password"))
        self.label_2.setText(_translate("MainWindow", "Sub System"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IP Address"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Port"))
        self.PB_New.setText(_translate("MainWindow", "New"))
        self.PB_Delete.setText(_translate("MainWindow", "Delete"))
        self.PB_Save_2.setText(_translate("MainWindow", "Save"))
        self.PB_Export.setText(_translate("MainWindow", "Export"))
        self.PB_Close.setText(_translate("MainWindow", "Close"))
        self.label_3.setText(_translate("MainWindow", "SSG"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Model No"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IP Address"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Port"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Drive"))
        self.PB_New_2.setText(_translate("MainWindow", "New"))
        self.PB_Delete_2.setText(_translate("MainWindow", "Delete"))
        self.PB_Save_3.setText(_translate("MainWindow", "Save"))
        self.PB_Export_2.setText(_translate("MainWindow", "Export"))
        self.PB_Close_2.setText(_translate("MainWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
