# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.uc'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtWidgets import QMainWindow, QApplication
from PyQt5.uic import loadUi
import sys

class main(QMainWindow):
    def __init__(self):
        super(main,self).__init__
        loadUi("main.ui", self)





if __name__ == "__main__":
    app = QApplication(sys.argv)
    ui = main()
    ui.show()
    app.exec_()


